---
image: "python:3.9"

test-api:
  only:
    - merge_requests
    - branches
  interruptible: true
  services:
    - postgres
  variables:
    POSTGRES_USER: mybelts
    POSTGRES_PASSWORD: mybelts
    POSTGRES_DB: mybelts
  script:
    - pip install -r requirements.txt
    - flake8 .
    - mypy .
    - PGHOST=postgres ./test-api
