---
image: "python:3.9"

test-api:
  only:
    - merge_requests
    - branches
  interruptible: true
  services:
    - postgres
  variables:
    POSTGRES_USER: mybelts
    POSTGRES_PASSWORD: mybelts
    POSTGRES_DB: mybelts
  script:
    - pip install -r requirements.txt
    - flake8 .
    - mypy .
    - PGHOST=postgres coverage run ./test-api
    - coverage report
    - coverage html
    - coverage xml
  artifacts:
    expose_as: 'Coverage'
    paths:
      - "htmlcov/"
    expire_in: 1 week
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  coverage: '/^TOTAL.*\s+(\d+\%)\s*$/'
