#!/usr/bin/env bash
set -Eeuo pipefail

cd "$(dirname $0)"

# parse arguments
if [ "$#" -ne 1 ]; then
  echo "Usage: $0 [dev|prod]"
  exit 1
fi
ENV=$1

# shellcheck source=dev.env
# shellcheck source=prod.env
source "${ENV}.env"

set -x

# build front-end
make -C front

# copy back-end sources, front-end build and migrations
mkdir tmp
trap 'rm -Rf tmp' EXIT ERR SIGINT SIGTERM
rsync -PHav --exclude=__pycache__ --exclude=.mypy_cache --exclude=.ruff_cache back tmp
rsync -PHav front/build tmp/front/
rsync -PHav --delete --exclude=env tmp/ "${HOST}:${WORKDIR}"

# migrate database and deploy back-end
# shellcheck disable=SC2087
ssh "${HOST}" <<EOF
set -x
cd ${WORKDIR}
cd back
python3 -m venv env
source env/bin/activate
pip install -r requirements.txt
alembic upgrade head
pkill gunicorn || true
gunicorn --daemon --workers=1 --worker-class=gevent --bind=0.0.0.0:20684 'app:create_app()' --error-logfile ~/mybelts-error.log
EOF
