#!/usr/bin/env bash
# Usage: copy this file to .git/hooks/

# Exit at first error
set -e

# To handle partially committed files, we must copy the staged changes to a
# separate location
# See also https://stackoverflow.com/a/36793330
TEMPDIR=$(mktemp -d)
trap 'rm -rf "$TEMPDIR"' EXIT SIGHUP SIGINT SIGQUIT SIGTERM
git checkout-index --prefix="$TEMPDIR/" -af

# Listing the changed files must be done from the git repository.

# flake8 only wants Python files so we filter by extension
git diff --cached --name-only --diff-filter=AM | grep '\.py$' |
    (cd $TEMPDIR; xargs --no-run-if-empty flake8 --config back/setup.cfg)
