#!/usr/bin/env bash
# Usage: copy this file to .git/hooks/

# Exit at first error
set -Eeu

# To handle partially committed files, we must copy the staged changes to a
# separate location
# See also https://stackoverflow.com/a/36793330
TEMPDIR=$(mktemp -d)
trap 'rm -rf "$TEMPDIR"' EXIT SIGHUP SIGINT SIGQUIT SIGTERM
git checkout-index --prefix="$TEMPDIR/" -af

# lint back
if ! git diff --cached --name-only --diff-filter=AM --quiet -- back; then
    pushd $TEMPDIR/back >/dev/null
    ruff check .
    popd >/dev/null
fi
