#!/usr/bin/env python3
import requests  # type: ignore
from alembic import command
from alembic.config import Config

from skills.schema import Base

API_URL = 'http://127.0.0.1/api'


def reset() -> None:
    print('Reseting database')
    Base.metadata.drop_all()
    command.stamp(Config('./alembic.ini'), 'base')
    command.upgrade(Config('./alembic.ini'), 'head')
    res = requests.get(API_URL + '/belts')
    res.raise_for_status()
    assert res.json() == {'belts': []}
    print('Reset Database')


def add_belts() -> None:
    print('Testing /belts resource')

    belt_names = [
        'White belt',
        'White belt',
        'Orange belt',
        'Green belt',
        'Blue belt',
        'Brown belt',
        'Black belt',
        'Transparent belt',
    ]

    # add belts
    ids = []
    for i, belt_name in enumerate(belt_names):
        res = requests.post(API_URL + '/belts', json={'name': belt_name})
        res.raise_for_status()
        j = res.json()
        print(j)
        assert j['belt']['name'] == belt_name
        assert j['belt']['rank'] == i + 1
        ids.append(j['belt']['id'])
    assert len(ids) == len(belt_names)

    # rename belt
    belt_names[1] = 'Yellow belt'
    res = requests.put(API_URL + f'/belts/{ids[1]}', json={'name': belt_names[1]})
    res.raise_for_status()
    j = res.json()
    print(j)
    assert j['belt']['id'] == ids[1]
    assert j['belt']['name'] == belt_names[1]
    assert j['belt']['rank'] == 2

    # change belt's color
    res = requests.put(API_URL + f'/belts/{ids[1]}', json={'color': 'yellow'})
    res.raise_for_status()
    j = res.json()
    print(j)
    assert j['belt']['id'] == ids[1]
    assert j['belt']['name'] == belt_names[1]
    assert j['belt']['rank'] == 2

    # delete belt
    res = requests.delete(API_URL + f'/belts/{ids[-1]}')
    res.raise_for_status()
    res = requests.get(API_URL + f'/belts/{ids[-1]}')
    assert res.status_code == 404
    belt_names.pop()
    ids.pop()

    # exchange rank with another belt
    res = requests.patch(API_URL + f'/belts/{ids[1]}/rank', json={'other_belt_id': ids[2]})
    res.raise_for_status()
    j = res.json()
    print(j)
    assert j['belt']['id'] == ids[1]
    assert j['belt']['name'] == belt_names[1]
    assert j['belt']['rank'] == 3

    # check rank of other belt
    res = requests.get(API_URL + f'/belts/{ids[2]}')
    res.raise_for_status()
    j = res.json()
    print(j)
    assert j['belt']['id'] == ids[2]
    assert j['belt']['name'] == belt_names[2]
    assert j['belt']['rank'] == 2

    # increase rank by 2
    res = requests.patch(API_URL + f'/belts/{ids[1]}/rank', json={'increase_by': 2})
    res.raise_for_status()
    j = res.json()
    print(j)
    assert j['belt']['id'] == ids[1]
    assert j['belt']['name'] == belt_names[1]
    assert j['belt']['rank'] == 5

    # check rank of the other two belts
    res = requests.get(API_URL + f'/belts/{ids[3]}')
    res.raise_for_status()
    j = res.json()
    print(j)
    assert j['belt']['id'] == ids[3]
    assert j['belt']['name'] == belt_names[3]
    assert j['belt']['rank'] == 3
    res = requests.get(API_URL + f'/belts/{ids[4]}')
    res.raise_for_status()
    j = res.json()
    print(j)
    assert j['belt']['id'] == ids[4]
    assert j['belt']['name'] == belt_names[4]
    assert j['belt']['rank'] == 4

    # move back to initial position
    res = requests.patch(API_URL + f'/belts/{ids[1]}/rank', json={'increase_by': -3})
    res.raise_for_status()
    j = res.json()
    print(j)
    assert j['belt']['id'] == ids[1]
    assert j['belt']['name'] == belt_names[1]
    assert j['belt']['rank'] == 2

    # check final state
    for i, belt_name in reversed(list(enumerate(belt_names))):
        res = requests.get(API_URL + f'/belts/{ids[i]}')
        res.raise_for_status()
        j = res.json()
        print(j)
        assert j['belt']['name'] == belt_name
        assert j['belt']['rank'] == i + 1

    print('Tested /belts resource')


def add_skill_domains() -> None:
    print('Testing resource /skill-domains')

    skill_domain_names = [
        'Algebra',
        'arithmetic',
        'Calculus',
        'Geometry',
        'Logic',
        'History',
    ]

    # add skill domains
    ids = []
    for skill_domain_name in skill_domain_names:
        res = requests.post(API_URL + '/skill-domains', json={'name': skill_domain_name})
        res.raise_for_status()
        j = res.json()
        print(j)
        assert j['skill_domain']['name'] == skill_domain_name
        ids.append(j['skill_domain']['id'])

    # rename skill domain
    skill_domain_names[1] = 'Arithmetic'
    res = requests.put(API_URL + f'/skill-domains/{ids[1]}', json={'name': skill_domain_names[1]})
    res.raise_for_status()
    j = res.json()
    print(j)
    assert j['skill_domain']['name'] == skill_domain_names[1]

    # delete skill domain
    skill_domain_names[1] = 'Arithmetic'
    res = requests.delete(API_URL + f'/skill-domains/{ids[-1]}')
    res.raise_for_status()
    res = requests.get(API_URL + f'/skill-domains/{ids[-1]}')
    assert res.status_code == 404
    ids.pop()
    skill_domain_names.pop()

    # check final state
    for i, skill_domain_name in reversed(list(enumerate(skill_domain_names))):
        res = requests.get(API_URL + f'/skill-domains/{ids[i]}')
        res.raise_for_status()
        j = res.json()
        print(j)
        assert j['skill_domain']['name'] == skill_domain_name

    print('Tested resource /skill-domains')


def main() -> None:
    reset()
    add_belts()
    add_skill_domains()


if __name__ == '__main__':
    main()
