[tool.ruff]
select = [
    "COM",  # flake8-commas
    "E",  # pycodestyle Error
    "F",  # Pyflakes
    "I",  # isort
    "Q",  # flake8-quotes
]
line-length = 119

[tool.ruff.flake8-quotes]
inline-quotes = "single"

[tool.ruff.isort]
split-on-trailing-comma = false

[tool.mypy]
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
no_implicit_optional = true
warn_unused_ignores = true
warn_return_any = true
warn_redundant_casts = true
plugins = "sqlmypy"
# enabled by default in dmypy
disable_error_code = "var-annotated"

[tool.coverage.report]
include = "mybelts/*"
